Módulo 4: NumPy para Operaciones Numéricas

**Autor:    Natalia Betancur Herrera**

Objetivos de la clase:

* Introducción a NumPy
* Importar NumPy y crear un array
* Operaciones con Arrays
* Producto de Matrices
* Indexación y Slicing
* Generación de Datos con NumPy
* Funciones útiles de análisis
* Funciones agregadas por eje



# Introducción a NumPy

¿Qué es NumPy?

NumPy (Numerical Python) es una biblioteca fundamental para el cálculo numérico en Python. Proporciona soporte para arrays multidimensionales y una amplia gama de funciones matemáticas optimizadas.


Instalación y uso en Colab

NumPy viene preinstalado en Google Colab, pero si trabajas en un entorno local, puedes instalarlo con:

In [ ]:
!pip install numpy

## Importar NumPy y crear un array

¿Qué es un Array?

Un array es una estructura de datos que almacena una colección de elementos del mismo tipo (generalmente números).

Los arrays en NumPy son fundamentales para realizar cálculos vectorizados (operaciones matemáticas realizadas en todo el array de una sola vez) y manipular grandes conjuntos de datos.

In [2]:
# Crear un array en NumPy

import numpy as np

# Crear un array 1D
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


¿Qué es una Matriz?

Una matriz es un tipo especial de array bidimensional. Es decir, un array que tiene dos dimensiones: filas y columnas. Las matrices son ampliamente utilizadas en álgebra lineal y para representar datos tabulares.


In [3]:
# Crear una matriz 2D

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz:")
print(matriz)

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##  Operaciones con Arrays

Operaciones Matemáticas Básicas

NumPy permite realizar operaciones matemáticas sobre arrays de manera eficiente y rápida. Las operaciones que se pueden realizar incluyen la suma, multiplicación, división, etc.

In [6]:
# Operaciones básicas con arrays


arr = np.array([1, 2, 3, 4, 5])

# Operación de suma
print("Suma de 10 a cada elemento:", arr + 10)

# Operación de resta
print("Resta:", arr - 2)

# Operación de multiplicación
print("Multiplicación por 2:", arr * 2)

# Operación de división
print("División:", arr / 2)

# Operación de potencia
print("Potencia:", arr ** 2)

# Raíz cuadrada de cada elemento
print("Raíz cuadrada:", np.sqrt(arr))

Suma de 10 a cada elemento: [11 12 13 14 15]
Resta: [-1  0  1  2  3]
Multiplicación por 2: [ 2  4  6  8 10]
División: [0.5 1.  1.5 2.  2.5]
Potencia: [ 1  4  9 16 25]
Raíz cuadrada: [1.         1.41421356 1.73205081 2.         2.23606798]


In [7]:
# Operaciones con dos arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


# Suma elemento a elemento
print("Suma de arrays:", a + b)

# Multiplicación elemento a elemento
print("Multiplicación elemento a elemento:", a * b)

Suma de arrays: [5 7 9]
Multiplicación elemento a elemento: [ 4 10 18]


## Producto de Matrices

El producto de matrices es una operación en la que se multiplican filas de la primera matriz por columnas de la segunda. A diferencia de la multiplicación elemento a elemento, esta operación combina filas y columnas y requiere que el número de columnas de la primera matriz coincida con el número de filas de la segunda.

In [9]:
# Definimos dos matrices A y B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Producto matricial con np.dot
producto = np.dot(A, B)
print("Producto de matrices (np.dot):")
print(producto)


# Producto con operador @
producto2 = A @ B
print("Producto de matrices (@):")
print(producto2)

Producto de matrices (np.dot):
[[19 22]
 [43 50]]
Producto de matrices (@):
[[19 22]
 [43 50]]


In [11]:
# Producto de matrices más complejo: A (3x2) * B (2x3)

# Matriz 3x2 con valores del 1 al 6
A = np.arange(1, 7).reshape(3, 2)

# Matriz 2x3 con valores del 7 al 12
B = np.arange(7, 13).reshape(2, 3)

# Producto de matrices A * B = C (3x3)
C = A @ B
print("Producto de matrices A (3x2) * B (2x3):")
print(C)

Producto de matrices A (3x2) * B (2x3):
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


## Indexación y Slicing




¿Qué es la Indexación?

La indexación es el proceso de acceder a elementos individuales dentro de un array o matriz utilizando su posición (índice).

In [12]:
# Crear un array de ejemplo
arr = np.array([10, 20, 30, 40, 50])

# Acceder al primer elemento
print("Primer elemento:", arr[0])

# Acceder al tercer elemento
print("Tercer elemento:", arr[2])

# Acceder al último elemento
print("Último elemento:", arr[-1])

Primer elemento: 10
Tercer elemento: 30
Último elemento: 50


¿Qué es el Slicing?

El slicing (o corte) permite extraer subconjuntos de un array utilizando una notación basada en rangos: inicio:fin:paso. Es muy útil cuando se desea trabajar solo con una parte del array o matriz.

In [13]:
# Crear un array del 0 al 9
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Elementos de la posición 2 a la 5 (índice 6 no incluido)
print("Elementos del índice 2 al 5:", arr[2:6])

# Elementos con paso de 2
print("Cada dos elementos:", arr[::2])

# Array invertido
print("Elementos del final hacia el inicio:", arr[::-1])

# Slicing en matrices
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a la primera fila
print("Primera fila:", mat[0])

# Acceder a la segunda columna
print("Segunda columna:", mat[:, 1])

# Extraer submatriz 2x2
print("Submatriz 2x2:")
print(mat[0:2, 0:2])

Elementos del índice 2 al 5: [2 3 4 5]
Cada dos elementos: [0 2 4 6 8]
Elementos del final hacia el inicio: [9 8 7 6 5 4 3 2 1 0]
Primera fila: [1 2 3]
Segunda columna: [2 5 8]
Submatriz 2x2:
[[1 2]
 [4 5]]


## Generación de Datos con NumPy


NumPy ofrece herramientas para generar datos, lo cual es útil para pruebas, simulaciones o entrenamiento de modelos. Las funciones más comunes incluyen:

* np.random.rand(): genera números aleatorios decimales entre 0 y 1.

* np.random.randint(inicio, fin, tamaño): genera números enteros aleatorios en un rango definido.

* np.linspace(inicio, fin, cantidad): crea un array con un número fijo de valores espaciados uniformemente entre dos extremos.

* np.arange(inicio, fin, paso): crea un array con valores dentro de un rango, definidos por un paso constante.

In [14]:
# Números aleatorios entre 0 y 1
random_numbers = np.random.rand(5)
print("Números aleatorios entre 0 y 1:", random_numbers)

# Números aleatorios enteros entre 1 y 100
enteros = np.random.randint(1, 100, size=5)
print("Enteros aleatorios entre 1 y 100:", enteros)

# Crear valores espaciados entre 0 y 10
linspace_arr = np.linspace(0, 10, 5)
print("Valores entre 0 y 10:", linspace_arr)

# Crear un array con valores desde 0 hasta 20 con paso 3
range_array = np.arange(0, 20, 3)
print("Rango de 0 a 20, paso 3:", range_array)

Números aleatorios entre 0 y 1: [0.07077354 0.8297099  0.70683826 0.2646506  0.34369739]
Enteros aleatorios entre 1 y 100: [98 12 78 61  6]
Valores entre 0 y 10: [ 0.   2.5  5.   7.5 10. ]
Rango de 0 a 20, paso 3: [ 0  3  6  9 12 15 18]


## Funciones útiles de análisis


Una vez que tienes datos, NumPy permite aplicar funciones estadísticas y analíticas de forma sencilla y rápida:

* np.sum(): suma todos los elementos.

* np.mean(): calcula la media (promedio).

* np.std(): calcula la desviación estándar (dispersión de los datos).

* np.max() y np.min(): devuelven el valor máximo y mínimo, respectivamente.

In [15]:
# Crear array
arr = np.array([3, 6, 2, 9, 5])

# Calcular suma, media y desviación estándar
print("Suma:", np.sum(arr))
print("Media:", np.mean(arr))
print("Desviación estándar:", np.std(arr))

# Máximo y mínimo
print("Máximo:", np.max(arr))
print("Mínimo:", np.min(arr))

Suma: 25
Media: 5.0
Desviación estándar: 2.449489742783178
Máximo: 9
Mínimo: 2


## Funciones agregadas por eje


Las funciones agregadas como sum(), mean(), max(), entre otras, pueden aplicarse no solo al array completo, sino también a lo largo de un eje específico usando el parámetro axis. Esto permite calcular estadísticas por fila o por columna, lo cual es muy útil en el análisis de datos.

* axis=0 → Aplica la función por columnas.

* axis=1 → Aplica la función por filas.

In [19]:
# Crear matriz 2x3
matriz = np.array([[1, 2, 3], [4, 5, 6]])

# Suma de cada columna
print("Suma por columnas:", np.sum(matriz, axis=0))

# Suma de cada fila
print("Suma por filas:", np.sum(matriz, axis=1))

# Media de cada fila
print("Media por filas:", np.mean(matriz, axis=1))

Suma por columnas: [5 7 9]
Suma por filas: [ 6 15]
Media por filas: [2. 5.]
